version: 2
jobs:
  lint:
    docker:
      - image: golangci/golangci-lint:v1.16
    steps:
      - checkout
      - run: golangci-lint run -v
  build:
    docker:
      - image: hacdias/caddy-plugin-test:latest
    steps:
      - checkout
      - run: caddy-build
workflows:
  version: 2
  build-workflow:
    jobs:
      - lint
      - build
